import { useState, useCallback, useMemo, useEffect, lazy, Suspense } from 'react';
import { useTranslation } from 'react-i18next';
import { useWeather } from '../../hooks/useWeather';
import { useParallelData } from '../../hooks/useParallelData';
import { useMoonPhase } from '../../hooks/useMoonPhase';
import { generateOmen, getOverallEnergy, getEnergyLabel } from '../../utils/omenGenerator';
import { useAuth } from '../../contexts/AuthContext';
import { useSubscription } from '../../contexts/SubscriptionContext';

const DataPanel = lazy(() => import('../DataPanel'));

interface OmenTabProps {
  onLoginRequired: () => void;
}

export default function OmenTab({ onLoginRequired }: OmenTabProps) {
  const { t, i18n } = useTranslation();
  const { session } = useAuth();
  const { isSubscribed, subscribe } = useSubscription();
  const [location, setLocation] = useState(null);
  const [locationError, setLocationError] = useState(null);
  const [showData, setShowData] = useState(false);
  const [dailyStyle, setDailyStyle] = useState<any>(null);
  const [styleLoading, setStyleLoading] = useState(false);

  const { data: weather, loading: weatherLoading, error: weatherError } = useWeather(
    location?.lat,
    location?.lon
  );
  const { earthquake, loading: parallelLoading, errors: parallelErrors } = useParallelData();
  const { data: moon } = useMoonPhase();

  // 서울 기본 좌표
  const DEFAULT_LOCATION = { lat: 37.5665, lon: 126.9780 };

  // 이전 저장된 위치 자동 불러오기, 없으면 서울 기본값
  useEffect(() => {
    if (!session?.access_token) {
      // 비로그인: 서울 기본값
      if (!location) setLocation(DEFAULT_LOCATION);
      return;
    }
    fetch('/api/profile', {
      headers: { Authorization: `Bearer ${session.access_token}` },
    })
      .then(r => r.json())
      .then(d => {
        if (d.profile?.last_lat && d.profile?.last_lon) {
          setLocation({ lat: d.profile.last_lat, lon: d.profile.last_lon });
        } else {
          setLocation(DEFAULT_LOCATION);
        }
      })
      .catch(() => {
        if (!location) setLocation(DEFAULT_LOCATION);
      });
  }, [session?.access_token]);

  const requestLocation = useCallback(() => {
    setLocationError(null);

    if (!navigator.geolocation) {
      setLocationError(t('location.notSupported'));
      return;
    }

    navigator.geolocation.getCurrentPosition(
      (position) => {
        const loc = {
          lat: position.coords.latitude,
          lon: position.coords.longitude,
        };
        setLocation(loc);
        // Save location to profile
        if (session?.access_token) {
          fetch('/api/profile', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
              'Authorization': `Bearer ${session.access_token}`,
            },
            body: JSON.stringify({ last_lat: loc.lat, last_lon: loc.lon }),
          }).catch(() => {});
        }
      },
      (error) => {
        switch (error.code) {
          case error.PERMISSION_DENIED:
            setLocationError(t('location.denied'));
            break;
          case error.POSITION_UNAVAILABLE:
            setLocationError(t('location.unavailable'));
            break;
          case error.TIMEOUT:
            setLocationError(t('location.timeout'));
            break;
          default:
            setLocationError(t('location.unavailable'));
        }
      },
      {
        enableHighAccuracy: false,
        timeout: 10000,
        maximumAge: 300000,
      }
    );
  }, [session?.access_token]);


  const isLoading = useMemo(
    () => location && (weatherLoading || parallelLoading),
    [location, weatherLoading, parallelLoading]
  );

  const omen = useMemo(() => {
    if (!weather || !moon || !earthquake) return null;
    return generateOmen(weather, moon, earthquake);
  }, [weather, moon, earthquake]);

  // Fetch daily reading (pre-generated by cron) or fall back to on-the-fly style
  useEffect(() => {
    if (!isSubscribed || !session?.access_token) return;
    if (dailyStyle) return;

    const fetchDailyReading = async () => {
      setStyleLoading(true);
      try {
        // Try pre-generated daily reading first
        const readingRes = await fetch('/api/daily-reading', {
          headers: { 'Authorization': `Bearer ${session.access_token}` },
        });
        if (readingRes.ok) {
          const { reading } = await readingRes.json();
          if (reading?.style_data) {
            setDailyStyle(reading.style_data);
            setStyleLoading(false);
            return;
          }
        }

        // Fall back to on-the-fly generation
        if (!omen?.main?.message) { setStyleLoading(false); return; }
        const energy = getOverallEnergy(weather!, moon!, earthquake!);
        const energyInfo = getEnergyLabel(energy);
        const res = await fetch('/api/daily-style', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${session.access_token}`,
          },
          body: JSON.stringify({
            omenMessage: omen.main.message,
            energy: energyInfo.label,
            lang: i18n.language,
          }),
        });
        if (res.ok) {
          const data = await res.json();
          if (data.success) setDailyStyle(data.data);
        }
      } catch (err) {
        console.error('Daily style error:', err);
      } finally {
        setStyleLoading(false);
      }
    };
    fetchDailyReading();
  }, [isSubscribed, omen, session?.access_token]);

  const toggleShowData = useCallback(() => {
    setShowData(prev => !prev);
  }, []);

  // 위치 요청 화면
  if (!location) {
    return (
      <div className="space-y-8">
        {/* Hero Section */}
        <section className="relative overflow-hidden rounded-2xl">
          <div
            className="flex min-h-[45vh] flex-col gap-6 bg-cover bg-center bg-no-repeat items-center justify-end pb-12 px-6 text-center"
            style={{
              backgroundImage: `linear-gradient(to top, #161022 10%, rgba(22, 16, 34, 0.6) 50%, rgba(0, 0, 0, 0.2) 100%), url("https://images.unsplash.com/photo-1507400492013-162706c8c05e?w=800&q=80")`,
            }}
          >
            <div className="flex flex-col gap-3 max-w-2xl">
              <h1 className="text-white text-4xl md:text-5xl font-bold leading-tight tracking-tighter">
                Divine <br />
                <span className="text-[#5b13ec] italic font-light">Omen</span>
              </h1>
              <p className="text-white/70 text-sm font-light leading-relaxed max-w-xs mx-auto">
                {t('omenTab.heroDesc')}
              </p>
            </div>
          </div>
        </section>

        {/* Location Request */}
        <section className="px-4">
          <div className="max-w-md mx-auto bg-[rgba(34,25,51,0.6)] backdrop-blur-xl rounded-2xl border border-white/10 p-6">
            <div className="text-center mb-6">
              <div className="h-16 w-16 rounded-full border border-[#5b13ec]/50 flex items-center justify-center shadow-[0_0_15px_rgba(91,19,236,0.3)] mx-auto mb-4">
                <span className="text-3xl">🔮</span>
              </div>
              <h3 className="text-white text-xl font-bold tracking-tight">{t('omenTab.locationSensing')}</h3>
              <p className="text-white/50 text-sm mt-2">
                {t('omenTab.locationAffects1')}<br />
                {t('omenTab.locationAffects2')}
              </p>
            </div>

            {locationError && (
              <div className="bg-red-500/10 backdrop-blur-xl rounded-xl border border-red-500/30 p-4 mb-6 text-center text-red-400 text-sm">
                {locationError}
              </div>
            )}

            <div className="space-y-3">
              <button
                onClick={requestLocation}
                className="w-full flex items-center justify-center rounded-full h-14 px-8 bg-[#5b13ec] text-white text-base font-bold tracking-widest uppercase transition-all shadow-[0_0_15px_rgba(91,19,236,0.3)] border border-[#5b13ec]/50 hover:scale-105 active:scale-95"
              >
                {t('location.startButton')}
              </button>

            </div>
          </div>
        </section>
      </div>
    );
  }

  // 로딩 화면
  if (isLoading) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center p-8">
        <div className="relative">
          <div className="absolute inset-0 rounded-full border border-[#5b13ec]/30 shadow-[0_0_30px_rgba(91,19,236,0.5)] animate-ping"></div>
          <div className="h-24 w-24 rounded-full border border-[#5b13ec]/50 flex items-center justify-center shadow-[0_0_15px_rgba(91,19,236,0.3)]">
            <span className="text-4xl animate-pulse">🔮</span>
          </div>
        </div>
        <h3 className="text-white text-xl font-bold mt-8 mb-2">{t('omenTab.readingSigns')}</h3>
        <p className="text-white/50 text-sm text-center max-w-xs">
          {t('omenTab.sensing')}
        </p>
        <div className="mt-6 flex gap-1">
          <div className="w-2 h-2 bg-[#5b13ec] rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
          <div className="w-2 h-2 bg-[#5b13ec] rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
          <div className="w-2 h-2 bg-[#5b13ec] rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
        </div>
      </div>
    );
  }

  // 에러 화면
  const hasError = weatherError || parallelErrors.nasa || parallelErrors.earthquake;
  if (hasError) {
    const errorMessages = [
      weatherError,
      parallelErrors.nasa,
      parallelErrors.earthquake,
    ].filter(Boolean);

    return (
      <div className="px-4 py-8">
        <div className="max-w-md mx-auto bg-[rgba(34,25,51,0.6)] backdrop-blur-xl rounded-2xl border border-red-500/30 p-8 text-center">
          <div className="h-16 w-16 rounded-full border border-red-500/50 flex items-center justify-center mx-auto mb-6">
            <span className="text-3xl">⚠️</span>
          </div>
          <h2 className="text-white text-xl font-bold mb-2">{t('omenTab.cannotRead')}</h2>
          <div className="text-white/50 text-sm mb-6 space-y-1">
            {errorMessages.map((msg, i) => (
              <p key={i}>{msg}</p>
            ))}
          </div>
          <button
            onClick={() => window.location.reload()}
            className="px-8 py-3 bg-[#5b13ec] text-white rounded-full font-bold uppercase tracking-widest text-sm hover:scale-105 transition-all shadow-[0_0_15px_rgba(91,19,236,0.3)]"
          >
            {t('omenTab.readAgain')}
          </button>
        </div>
      </div>
    );
  }

  // 결과 화면
  const energy = getOverallEnergy(weather, moon, earthquake);
  const energyInfo = getEnergyLabel(energy);

  return (
    <div className="space-y-8 pb-8">
      {/* 위치 표시 */}
      {weather?.cityName && (
        <p className="text-white/40 text-sm text-center">
          {t('omenTab.underSky', { city: weather.cityName })}
        </p>
      )}

      {/* 메인 괘 카드 */}
      <section className="px-4">
        <div className="max-w-md mx-auto bg-[rgba(34,25,51,0.6)] backdrop-blur-xl rounded-2xl border border-white/10 p-6">
          {/* 에너지 지표 */}
          <div className="flex justify-between items-center mb-6">
            <span className="text-white/40 text-xs uppercase tracking-widest">{t('omenCard.energyFlow')}</span>
            <div className="flex items-center gap-2">
              <div className="w-24 h-2 bg-white/10 rounded-full overflow-hidden">
                <div
                  className="h-full bg-gradient-to-r from-[#5b13ec] to-purple-400 transition-all duration-1000"
                  style={{ width: `${energy}%` }}
                />
              </div>
              <span className={`text-sm font-medium ${
                energyInfo.label === '대길' ? 'text-yellow-400' :
                energyInfo.label === '길' ? 'text-green-400' :
                energyInfo.label === '평' ? 'text-white/60' :
                energyInfo.label === '소흉' ? 'text-orange-400' :
                'text-red-400'
              }`}>
                {energyInfo.label}
              </span>
            </div>
          </div>

          {/* 메인 메시지 */}
          <div className="text-center mb-6">
            <div className="h-12 w-12 rounded-full border border-[#5b13ec]/50 flex items-center justify-center shadow-[0_0_15px_rgba(91,19,236,0.3)] mx-auto mb-4">
              <span className="text-xl">✨</span>
            </div>
            <p className="text-white/70 text-lg italic leading-relaxed">
              "{omen?.main?.message}"
            </p>
          </div>

          {/* 타임스탬프 */}
          <div className="pt-4 border-t border-white/10 text-center">
            <p className="text-white/30 text-xs">
              {omen?.timestamp?.toLocaleString(i18n.language === 'ko' ? 'ko-KR' : 'en-US', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
                hour: '2-digit',
                minute: '2-digit',
              })} {t('omenCard.celestialSign')}
            </p>
          </div>
        </div>
      </section>

      {/* 세부 괘 */}
      <section className="px-4">
        <div className="max-w-md mx-auto space-y-4">
          <h4 className="text-white font-bold uppercase tracking-widest text-xs text-[#5b13ec] px-1">{t('omenTab.detailedOmens')}</h4>
          {omen?.details?.map((detail, index) => (
            <div
              key={index}
              className="bg-[rgba(34,25,51,0.6)] backdrop-blur-xl rounded-2xl border border-white/10 p-5"
            >
              <div className="flex items-center gap-3 mb-3">
                <span className="text-2xl">{detail.icon}</span>
                <span className="text-white font-bold">{detail.category}</span>
              </div>
              <p className="text-white/60 text-sm leading-relaxed">
                {detail.message}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Daily Style - Premium */}
      <section className="px-4">
        <div className="max-w-md mx-auto">
          {isSubscribed ? (
            // Subscriber: show daily style
            <div className="bg-[rgba(34,25,51,0.6)] backdrop-blur-xl rounded-2xl border border-[#5b13ec]/30 p-5">
              <div className="flex items-center gap-2 mb-4">
                <span className="text-lg">👔</span>
                <h4 className="text-white font-bold text-sm">{t('sub.dailyStyleTitle')}</h4>
                <span className="ml-auto text-[10px] text-[#5b13ec] bg-[#5b13ec]/10 px-2 py-0.5 rounded-full font-bold uppercase tracking-wider">
                  {t('sub.badge')}
                </span>
              </div>
              {styleLoading ? (
                <div className="text-center py-6">
                  <div className="flex gap-1 justify-center mb-2">
                    <div className="w-2 h-2 bg-[#5b13ec] rounded-full animate-bounce" style={{ animationDelay: '0ms' }} />
                    <div className="w-2 h-2 bg-[#5b13ec] rounded-full animate-bounce" style={{ animationDelay: '150ms' }} />
                    <div className="w-2 h-2 bg-[#5b13ec] rounded-full animate-bounce" style={{ animationDelay: '300ms' }} />
                  </div>
                  <p className="text-white/40 text-sm">{t('sub.loadingStyle')}</p>
                </div>
              ) : dailyStyle ? (
                <div className="space-y-4">
                  <p className="text-white/80 text-base italic">"{dailyStyle.headline}"</p>
                  <p className="text-white/60 text-sm leading-relaxed">{dailyStyle.style}</p>
                  <div className="flex flex-wrap gap-2">
                    <span className="text-white/40 text-xs">{t('sub.styleColors')}:</span>
                    {dailyStyle.colors?.map((color: string, i: number) => (
                      <span key={i} className="text-[#5b13ec] text-xs bg-[#5b13ec]/10 px-2 py-0.5 rounded-full">
                        {color}
                      </span>
                    ))}
                  </div>
                  <div className="grid grid-cols-2 gap-3 pt-2 border-t border-white/10">
                    <div>
                      <span className="text-white/40 text-xs block mb-1">{t('sub.styleItem')}</span>
                      <span className="text-white text-sm">{dailyStyle.item}</span>
                    </div>
                    <div>
                      <span className="text-white/40 text-xs block mb-1">{t('sub.styleTip')}</span>
                      <span className="text-white text-sm">{dailyStyle.tip}</span>
                    </div>
                  </div>
                </div>
              ) : null}
            </div>
          ) : (
            // Non-subscriber: locked preview with blur
            <div className="relative overflow-hidden rounded-2xl border border-white/10">
              {/* Blurred fake content */}
              <div className="bg-[rgba(34,25,51,0.6)] backdrop-blur-xl p-5 blur-sm select-none pointer-events-none">
                <div className="flex items-center gap-2 mb-4">
                  <span className="text-lg">👔</span>
                  <span className="text-white font-bold text-sm">{t('sub.dailyStyleTitle')}</span>
                </div>
                <p className="text-white/60 text-sm mb-3">오늘의 에너지에 맞는 스타일을 추천해드립니다. 보라색 계열의 색상이 오늘의 기운과 잘 어울립니다.</p>
                <div className="flex gap-2">
                  <span className="text-xs bg-purple-500/20 px-2 py-1 rounded text-purple-300">Purple</span>
                  <span className="text-xs bg-blue-500/20 px-2 py-1 rounded text-blue-300">Navy</span>
                  <span className="text-xs bg-gray-500/20 px-2 py-1 rounded text-gray-300">Silver</span>
                </div>
              </div>
              {/* Lock overlay */}
              <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/40 backdrop-blur-[2px]">
                <div className="h-12 w-12 rounded-full border border-[#5b13ec]/50 flex items-center justify-center mb-3 shadow-[0_0_15px_rgba(91,19,236,0.3)]">
                  <span className="text-xl">🔒</span>
                </div>
                <p className="text-white/70 text-sm font-medium mb-1">{t('sub.locked')}</p>
                <button
                  onClick={() => {
                    if (!session) { onLoginRequired(); return; }
                    subscribe();
                  }}
                  className="mt-2 px-6 py-2 bg-[#5b13ec] hover:bg-[#4a0fd0] rounded-full text-white text-xs font-bold tracking-wide transition-all shadow-[0_0_15px_rgba(91,19,236,0.4)]"
                >
                  {t('sub.unlockStyle')}
                </button>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* 천기 원천 토글 */}
      <div className="text-center">
        <button
          onClick={toggleShowData}
          className="px-6 py-2 text-[#5b13ec] text-sm hover:text-white transition-colors"
        >
          {showData ? `${t('data.source')} ▲` : `${t('data.source')} ▼`}
        </button>
      </div>

      {showData && (
        <div className="px-4 animate-fade-in">
          <Suspense fallback={
            <div className="max-w-md mx-auto bg-[rgba(34,25,51,0.6)] backdrop-blur-xl rounded-2xl border border-white/10 p-6 text-center text-white/50">
              {t('omenTab.gatheringEnergy')}
            </div>
          }>
            <DataPanel
              weather={weather}
              moon={moon}
              earthquake={earthquake}
              nasa={null}
            />
          </Suspense>
        </div>
      )}
    </div>
  );
}
